# Generated by Django 2.2 on 2019-05-05 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Character',
        ),
    ]
