# Generated by Django 2.2 on 2019-05-05 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_character'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Character',
        ),
    ]
